version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: notion-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "--user=${MYSQL_USER}",
          "--password=${MYSQL_PASSWORD}",
          "-e",
          "SHOW DATABASES;",
        ]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: always

  api-todo:
    build: .
    container_name: notion-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    depends_on:
      db:
        condition: "service_healthy"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"

volumes:
  db_data:
