version: 1
services:
  - type: web
    name: notion-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: ${MYSQL_ROOT_PASSWORD}
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE}
      - key: MYSQL_USER
        value: ${MYSQL_USER}
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}
      - key: DATABASE_URL
        value: mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@notion-db:3306/${MYSQL_DATABASE}
    ports:
      - 8000
    dependsOn:
      - notion-db

  - type: database
    name: notion-db
    env: mysql
    plan: free
    disk:
      sizeGB: 10
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: ${MYSQL_ROOT_PASSWORD}
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE}
      - key: MYSQL_USER
        value: ${MYSQL_USER}
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}
